export const ACTIONS = {
  USER_LOGIN: 'USER_LOGIN',
  USER_REGISTER: 'USER_REGISTER',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_CHANGE_AVATAR: 'USER_CHANGE_AVATAR',
  USER_CHANGE_USERNAME: 'USER_CHANGE_USERNAME',
  USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
  USER_CHANGE_EMAIL: 'USER_CHANGE_EMAIL',
  USER_UPDATE_STATS: 'USER_UPDATE_STATS',
};

export const DEFAULT = {
  AVATAR: 'man.png',
};

export const CONFIG = {
  SERVER: {
    URL: 'http://localhost',
    PORT: '8080',
  }
}
